DROP DATABASE IF EXISTS Comuctiva;
CREATE DATABASE Comuctiva;
Use Comuctiva;

CREATE TABLE Tipo_Documento(
	Id_TipDocu TINYINT (3) PRIMARY KEY AUTO_INCREMENT,
    Tipo VARCHAR (30) NOT NULL
);
CREATE TABLE Rol(
	Id_Rol INT (10) PRIMARY KEY AUTO_INCREMENT,
    Nom_Rol VARCHAR (30)
);
CREATE TABLE Vias(
	Id_Vias INT (10) PRIMARY KEY AUTO_INCREMENT,
    Tipo VARCHAR (20) NOT NULL
);
CREATE TABLE Muni(
	Id_Muni INT (10) PRIMARY KEY AUTO_INCREMENT,
    Nom VARCHAR (50) NOT NULL
);

CREATE TABLE Transportadora(
	Id_Transpor INT (10) PRIMARY KEY AUTO_INCREMENT,
    NombreT VARCHAR (30) NOT NULL,
    Logo VARCHAR (30) NOT NULL,
    Telefono VARCHAR (20) NOT NULL,
    Correo VARCHAR (50) NOT NULL,
    Direcc VARCHAR (50) NOT NULL,
    Sitio_Web VARCHAR (50) NOT NULL
);
CREATE TABLE Unidad_Medida(
	Id_Medida INT (10) PRIMARY KEY AUTO_INCREMENT,
    Tip_Medida VARCHAR (20) NOT NULL 
);
CREATE TABLE Descuentos(
	Id_Descu INT (10)PRIMARY KEY AUTO_INCREMENT, 
	Descripcion VARCHAR (50) NOT NULL,
	Fec_Des DATE NOT NULL,
    Valor DECIMAL (10,2) NOT NULL
);
CREATE TABLE Tipo_De_Pago(
	Id_Tip_Pago INT (10) PRIMARY KEY AUTO_INCREMENT,
    Tipos VARCHAR (20) NOT NULL
);

