INSERT INTO Rol (Nom_Rol) VALUES ("Cliente"),("Vendedor"),("Administrador");
INSERT INTO Tip_Doc (Tipo) VALUES ("Cedula de Cuidadania"),("Pasaporte"),("Tarjeta de Identidad"),("Cedula de Extranjeria");
INSERT INTO Vias (Tipo) VALUES ("Calle"),("Carrera"),("Avenida"),("Transversal");
INSERT INTO Unidad_Medida (Tip_Medida) VALUES ("Libra"),("Kilo"),("Bulto"),("Unidad"),("Litro"),("Gramo");
INSERT INTO Tipo_De_Pago (Tipos) VALUES ("Tarjeta de Credito"),("Tarjeta de Debito"),("PSE"),("Efectivo"),("PayPal"),("Nequi"),("Daviplata");

INSERT INTO Barrio (Barr_Vere) VALUES ("Barrio"),("Vereda"),("Sector");

INSERT INTO Pedidos (Estado) VALUES ("En espera"),("En proceso"),("Enviado"),("Entregado"),("Cancelado"),("Cerrado"),("Devuelto");

INSERT INTO Guia_de_Envio (Obser) VALUES ("delicado"), ("peligro"), ("fragil"), ("ligero"), ("pesado"), ("delicado");
/*Departamentos :D*/

INSERT INTO Dep (ID_Dep,Nom) VALUES (11,"Bogotá, D.C.");
INSERT INTO Dep (ID_Dep,Nom) VALUES (25,"Cundinamarca");

/*Muni :D*/

INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25183,"CHOCONTÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25426,"MACHETA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25436,"MANTA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25736,"SESQUILÉ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25772,"SUESCA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25807,"TIBIRITA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25873,"VILLAPINZÓN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25001,"AGUA DE DIOS",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25307,"GIRARDOT",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25324,"GUATAQUÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25368,"JERUSALÉN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25483,"NARIÑO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25488,"NILO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25612,"RICAURTE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25815,"TOCAIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25148,"CAPARRAPÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25320,"GUADUAS",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25572,"PUERTO SALGAR",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25019,"ALBÁN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25398,"LA PEÑA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25402,"LA VEGA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25489,"NIMAIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25491,"NOCAIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25592,"QUEBRADANEGRA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25658,"SAN FRANCISCO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25718,"SASAIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25777,"SUPATÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25851,"ÚTICA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25862,"VERGARA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25875,"VILLETA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25293,"GACHALA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25297,"GACHETA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25299,"GAMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25322,"GUASCA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25326,"GUATAVITA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25372,"JUNÍN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25377,"LA CALERA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25839,"UBALÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25086,"BELTRÁN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25095,"BITUIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25168,"CHAGUANÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25328,"GUAYABAL DE SIQUIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25580,"PULI",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25662,"SAN JUAN DE RÍO SECO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25867,"VIANÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25438,"MEDINA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25530,"PARATEBUENO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25151,"CAQUEZA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25178,"CHIPAQUE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25181,"CHOACHÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25279,"FOMEQUE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25281,"FOSCA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25335,"GUAYABETAL",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25339,"GUTIÉRREZ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25594,"QUETAME",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25841,"UBAQUE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25845,"UNE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25258,"EL PEÑÓN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25394,"LA PALMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25513,"PACHO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25518,"PAIME",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25653,"SAN CAYETANO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25823,"TOPAIPI",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25871,"VILLAGOMEZ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25885,"YACOPÍ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25126,"CAJICÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25175,"CHÍA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25200,"COGUA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25295,"GACHANCIPÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25486,"NEMOCoN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25758,"SOPÓ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25785,"TABIO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25817,"TOCANCIPÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25899,"ZIPAQUIRÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25099,"BOJACÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25214,"COTA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25260,"EL ROSAL",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25269,"FACATATIVÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25286,"FUNZA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25430,"MADRID",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25473,"MOSQUERA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25769,"SUBACHOQUE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25799,"TENJO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25898,"ZIPACoN",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25740,"SIBATÉ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25754,"SOACHA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25053,"ARBELÁEZ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25120,"CABRERA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25290,"FUSAGASUGÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25312,"GRANADA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25524,"PANDI",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25535,"PASCA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25649,"SAN BERNARDO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25743,"SILVANIA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25805,"TIBACUY",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25506,"VENECIA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25035,"ANAPOIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25040,"ANOLAIMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25599,"APULO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25123,"CACHIPAY",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25245,"EL COLEGIO",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25386,"LA MESA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25596,"QUIPILE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25645,"SAN ANTONIO DE TEQUENDAMA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25797,"TENA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25878,"VIOTÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25154,"CARMEN DE CARUPA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25224,"CUCUNUBÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25288,"FÚQUENE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25317,"GUACHETÁ",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25407,"LENGUAZAQUE",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25745,"SIMIJACA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25779,"SUSA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25781,"SUTATAUSA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25793,"TAUSA",25);
INSERT INTO Muni (ID_Muni,Nom,ID_Dep)VALUES (25843,"UBATE",25);








